"""
sim_framework.py

Molecular Dynamics (MD) Simulation Framework for Stress-Controlled Diffusion.

PURPOSE:
    This script initializes and executes a 'rerun' simulation where a 
    specific configuration of Self-Interstitial Atoms (SIAs), extracted 
    from a previous analysis, is evolved under specific temperature and 
    stress conditions.

    It handles the path mapping between a local workstation (analysis) 
    and an HPC cluster (execution), ensuring that even if the restart 
    files are missing locally, the metadata correctly points to the 
    HPC scratch space.

WORKFLOW ALIGNMENT:
    1. Source Data: Always pulled from T800 simulations (via metadata.json).
    2. Target Data: Can be T700, T800, or T900 as specified in metadata.
    3. Input: A JSON metadata file generated by the pre-processing script.

USAGE:
    # 1. DRY RUN (Local Testing)
    # Checks path logic and metadata parsing without calling LAMMPS.
    python /home/Ethan/Projects/prec_interactions/simulations/02_diffusion.py --meta ~/Projects/prec_interactions/data/rerun/R30_S150_T700/metadata.json

    mpirun -np 16 python /home/Ethan/Projects/prec_interactions/simulations/02_diffusion.py --meta ~/Projects/prec_interactions/data/rerun/R30_S150_T700/metadata.json --bench 0

    # 2. FULL HPC RUN (Slurm/MPI)
    # Uses the HPC paths defined in the JSON to locate the .restart file.
    mpirun -np 128 python sim_framework.py --meta /mnt/parscratch/users/mtp24ele/private/prec_interactions/data/rerun/R30_S150_T700/metadata.json

ARGUMENTS:
    --meta      : (str) Path to the metadata.json file for the specific rerun case.
    --bench     : (int) Optional benchmark mode (0 or 1).
    --run_time  : (int) Optional override for total timesteps (default: 1,500,000).

ENVIRONMENT LOGIC:
    - If running on local path (/home/Ethan), the script references 'RestartFile_local'.
    - If running elsewhere (HPC), it references 'RestartFile_HPC'.
    - Results are written to: .../data/rerun_results/diffusion_T{temp}_ST{stress}_R{radius}_N{seed}/
"""
import numpy as np
import json
import yaml
import shutil
import argparse
from pathlib import Path
from dataclasses import dataclass, field, asdict
from mpi4py import MPI

@dataclass
class SimParams:
    radius: int
    target_stress: float
    step: int
    temperature: int
    restart_file_local: Path
    restart_file_HPC: Path
    num_sias: int
    box_bounds: dict
    atoms_file_local: Path
    atoms_file_HPC: Path
    original_sim_dir: Path
    potential_path: Path
    bench: int = None
    thermo_time: int = 10_000
    run_time: int = 1_500_000
    dt: float = 0.001
    species: str = "Fe"
    thermo_freq: int = 100
    dump_freq: int = 1000
    restart_freq: int = 10_000
    num_cores: int = field(default=1)
    random_seed: int = field(default_factory=lambda: 1234)

    def __post_init__(self):
        if self.bench == 0:
            self.thermo_time = 1
            self.run_time = 1
        elif self.bench == 1:
            self.thermo_time = 500
            self.run_time = 500

    @property
    def case_name(self) -> str:
        return f"diffusion_T{self.temperature}_ST{int(self.target_stress)}_R{self.radius}_N{self.random_seed}"

def get_project_root() -> Path:
    """Finds the 'prec_interactions' root directory."""
    current_path = Path(__file__).resolve()
    for parent in current_path.parents:
        if parent.name == "prec_interactions":
            return parent
    return current_path.parent.parent

def load_metadata(file_path: Path) -> dict:
    if not file_path.exists():
        raise FileNotFoundError(f"Metadata file not found: {file_path}")
    
    with open(file_path) as f:
        if file_path.suffix in [".yaml", ".yml"]:
            return yaml.safe_load(f)
        return json.load(f)

def parse_arguments() -> SimParams:
    parser = argparse.ArgumentParser(description="MD simulation runner")
    parser.add_argument("--meta", type=str, required=True, help="Path to metadata JSON/YAML")
    parser.add_argument("--bench", type=int, choices=[0, 1], default=None)
    parser.add_argument("--run_time", type=int, default=None)
    args = parser.parse_args()

    # Resolve the meta path to absolute immediately
    meta_path = Path(args.meta).resolve()
    meta = load_metadata(meta_path)
    root = get_project_root()

    return SimParams(
        radius=meta["Radius"],
        target_stress=meta["TargetStress"],
        step=meta["Step"],
        temperature=meta["Temperature"],
        restart_file_local=Path(meta["RestartFile_local"]),
        restart_file_HPC=Path(meta["RestartFile_HPC"]),
        atoms_file_local=Path(meta["AtomsFile_local"]),
        atoms_file_HPC=Path(meta["AtomsFile_HPC"]),
        num_sias=meta["NumSIAs"],
        box_bounds=meta["BoxBounds"],
        original_sim_dir=Path(meta["OriginalSimDir"]),
        potential_path=root / "potentials" / "mendelev03.fs",
        bench=args.bench,
        run_time=args.run_time if args.run_time is not None else 1_500_000,
    )

def init_paths(params: SimParams) -> dict:
    # Ensure the output directory is created relative to the original simulation directory
    base = params.original_sim_dir.parent / params.case_name
    
    paths = {
        "base": base,
        "logs": base / "logs",
        "dump": base / "dump",
        "restart": base / "restart",
        "output": base / "output",
        "inputs": base / "inputs",
        "metadata": base / "run_config.yaml"
    }
    
    for p in paths.values():
        if not p.suffix: p.mkdir(parents=True, exist_ok=True)

    # REPLACED: Check existence rather than hardcoded usernames
    if params.restart_file_local.exists():
        src_restart, src_atoms = params.restart_file_local, params.atoms_file_local
    else:
        src_restart, src_atoms = params.restart_file_HPC, params.atoms_file_HPC

    # Copy files
    if src_restart.exists():
        shutil.copy(src_restart, paths["inputs"] / "input.restart")
    if src_atoms.exists():
        shutil.copy(src_atoms, paths["inputs"] / "atoms.txt")

    return paths, src_restart, src_atoms

def populate(lmp, filepath):
    """Injects atoms from text file into the LAMMPS instance."""
    coords = np.loadtxt(filepath)
    # Use rank 0 to print status
    if MPI.COMM_WORLD.Get_rank() == 0:
        print(f"--- Populating {len(coords)} SIAs ---")
    
    for row in coords:
        x, y, z = row
        lmp.cmd.create_atoms(1, "single", x, y, z)

    lmp.cmd.group("mobgrp", "type", 1)
    lmp.cmd.group("all", "union", "fixgrp", "mobgrp")

def run_simulation(params: SimParams, paths: dict, restart_src: Path, atoms_src: Path, comm) -> None:

    # LAMMPS execution logic...
    from lammps import lammps
    lmp = lammps(comm=comm)
    
    lmp.cmd.log(paths["logs"] / "setup.log")
    
    lmp.cmd.processors("*", 2, "*")
    lmp.cmd.units("metal")
    lmp.cmd.dimension(3)
    lmp.cmd.boundary("p", "s", "p") # Set shrink-wrapped boundaries along the y-direction
    lmp.cmd.atom_style("atomic")
    lmp.cmd.atom_modify("map", "yes")
    lmp.cmd.timestep(params.dt)

    lmp.cmd.read_restart(str(paths["inputs"] / "input.restart"))

    # ===========================
    # Define the interatomic potential
    # ===========================
    lmp.cmd.pair_style("eam/fs")
    lmp.cmd.pair_coeff("* *", str(params.potential_path), params.species, params.species, params.species, params.species)

    lmp.cmd.neighbor(2.0, "bin")
    lmp.cmd.neigh_modify("delay", 10, "check", "yes")

    # ===========================
    # Define groups
    # ===========================
    lmp.cmd.group("mobgrp", "type", "1")
    lmp.cmd.group("topgrp", "type", "2")
    lmp.cmd.group("botgrp", "type", "3")
    lmp.cmd.group("precgrp", "type", "4")
    lmp.cmd.group("fixgrp", "union", "precgrp", "topgrp", "botgrp")
    lmp.cmd.group("all", "union", "fixgrp", "mobgrp")

    # ===========================
    # Computes
    # ===========================
    lmp.cmd.compute("stress", "all", "stress/atom", "NULL")
    lmp.cmd.compute("mobtemp", "mobgrp", "temp")
    lmp.cmd.compute("pe", "all", "pe/atom")
    lmp.cmd.compute("ke", "all", "ke/atom")

    lmp.cmd.compute("mobstressXX", "mobgrp", "reduce", "sum", "c_stress[1]")
    lmp.cmd.compute("mobstressYY", "mobgrp", "reduce", "sum", "c_stress[2]")
    lmp.cmd.compute("mobstressZZ", "mobgrp", "reduce", "sum", "c_stress[3]")
    lmp.cmd.compute("mobstressXY", "mobgrp", "reduce", "sum", "c_stress[4]")
    lmp.cmd.compute("mobstressYZ", "mobgrp", "reduce", "sum", "c_stress[5]")
    lmp.cmd.compute("mobstressXZ", "mobgrp", "reduce", "sum", "c_stress[6]")

    lmp.cmd.compute("mobpetot", "mobgrp", "reduce", "sum", "c_pe")
    lmp.cmd.compute("mobketot", "mobgrp", "reduce", "sum", "c_ke")

    # ===========================
    # Minimize
    # ===========================
    lmp.cmd.fix(1, "fixgrp", "setforce", 0.0, 0.0, 0.0)

    lmp.cmd.reset_timestep(0)
    lmp.cmd.thermo_style("custom", "step", "temp", "pe", "etotal", "pxx", "pyy", "pzz", "pxy", "pyz", "pxz", "lx", "ly", "lz")
    lmp.cmd.thermo_modify("temp", "mobtemp")
    lmp.cmd.thermo(1)

    lmp.cmd.min_style("cg")
    lmp.cmd.minimize(1e-4, 1e-6, 5000, 10000)

    lmp.cmd.write_dump(
        "all", "custom", paths["output"] / "minimized_initial.dump",
        "id", "type", "x", "y", "z",
        "c_pe", "c_ke",
        "c_stress[1]", "c_stress[2]", "c_stress[3]", "c_stress[4]", "c_stress[5]", "c_stress[6]",
    )

    # ===========================
    # Populate
    # ===========================
    populate(lmp, atoms_src)

    # ===========================
    # Minimize with SIAs
    # ===========================
    lmp.cmd.reset_timestep(0)

    lmp.cmd.min_style("fire")
    lmp.cmd.minimize(1e-4, 1e-6, 2000, 10000)

    lmp.cmd.min_style("cg")
    lmp.cmd.minimize(1e-4, 1e-6, 5000, 10000)

    lmp.cmd.write_dump(
        "all", "custom", paths["output"] / "minimized_final.dump",
        "id", "type", "x", "y", "z",
        "c_pe", "c_ke",
        "c_stress[1]", "c_stress[2]", "c_stress[3]", "c_stress[4]", "c_stress[5]", "c_stress[6]",
    )

    # ===========================
    # Setup Outputs
    # ===========================
    lmp.cmd.reset_timestep(0)
    lmp.cmd.log(paths["logs"] / "diffusion.log")

    lmp.cmd.thermo(params.thermo_freq)

    lmp.cmd.thermo_style(
        "custom", "step", "temp", "pe", "etotal", 
        "pxx", "pyy", "pzz", "pxy", "pyz", "pxz",
        "c_mobpetot", "c_mobketot", "c_mobtemp",
        "c_mobstressXX", "c_mobstressYY", "c_mobstressZZ",
        "c_mobstressXY", "c_mobstressYZ", "c_mobstressXZ"
    )
    lmp.cmd.thermo_modify("temp", "mobtemp")

    lmp.cmd.dump("dump", "all", "custom", params.dump_freq, paths["dump"] / "dump_*.lammpstrj", 
                 "id", "type", "x", "y", "z", "vx", "vy", "vz", "fx", "fy", "fz", "c_pe", "c_ke", "c_stress[1]", "c_stress[2]", "c_stress[3]", "c_stress[4]", "c_stress[5]", "c_stress[6]"
                 )
    
    lmp.cmd.restart(params.restart_freq, paths["restart"] / "*.restart")

    # ===========================
    # Ramping Temperature
    # ===========================
    lmp.cmd.velocity("mobgrp", "create", 10.0, params.random_seed, "mom", "yes", "rot", "yes", "dist", "gaussian")
    lmp.cmd.fix(2, "mobgrp", "nvt", "temp", 10.0, params.temperature, params.dt*10)
    lmp.cmd.fix_modify(2, "temp", "mobtemp")

    lmp.cmd.run(params.thermo_time)
    lmp.cmd.unfix(2)

    # ===========================
    # Holding Temperature
    # ===========================
    lmp.cmd.fix(2, "mobgrp", "nvt", "temp", params.temperature, params.temperature, params.dt*100)
    lmp.cmd.fix_modify(2, "temp", "mobtemp")

    lmp.cmd.run(params.run_time)

def main():
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    
    params = None
    if rank == 0:
        try:
            params = parse_arguments()
        except Exception as e:
            print(f"Rank 0 Error: {e}")
            comm.Abort()

    params = comm.bcast(params, root=0)
    params.num_cores = comm.Get_size()
    
    # init_paths now returns the chosen sources
    paths, chosen_restart, chosen_atoms = init_paths(params)
    
    if rank == 0:
        meta_dict = asdict(params)
        for k, v in meta_dict.items():
            if isinstance(v, Path): meta_dict[k] = str(v)
        with open(paths["metadata"], "w") as f:
            yaml.dump(meta_dict, f)

    run_simulation(params, paths, chosen_restart, chosen_atoms, comm)

if __name__ == "__main__":
    main()